version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: postgres
    ports:
      - 5433:5432
    volumes:
      - /data/postgres/postgresql:/var/lib/postgresql
      - /data/postgres/data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar 
    networks:
      - sonar-net

  sonar:
    image: sonarqube:7.9.2-community
    container_name: sonar
    depends_on: 
      - postgres
    volumes:
      - /data/sonarqube/extensions:/opt/sonarqube/extensions
      - /data/sonarqube/logs:/opt/sonarqube/logs
      - /data/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube/conf:/opt/sonarqube/conf
    ports:
      - 9000:9000    
    environment:
      TZ: Asia/Shanghai
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
    networks:
      - sonar-net

networks:
  sonar-net:
    driver: bridge
