version: "3"
services:
  nginx_master:
    container_name: nginx_keepalived_master_01
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx-master/index-master.html:/usr/share/nginx/html/index.html
      - ./nginx-master/favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./nginx-master/keepalived-master.conf:/etc/keepalived/keepalived.conf
    environment:
      TZ: Asia/Shanghai
    networks:
      static-network:
        ipv4_address: 172.30.128.2
    cap_add: 
      - NET_ADMIN
  nginx_slave:
    container_name: nginx_keepalived_slave_01
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx-slave/index-slave.html:/usr/share/nginx/html/index.html
      - ./nginx-slave/favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./nginx-slave/keepalived-slave.conf:/etc/keepalived/keepalived.conf
    environment:
      TZ: Asia/Shanghai
    networks:
      static-network:
        ipv4_address: 172.30.128.3
    cap_add: 
        - NET_ADMIN
  proxy:
    container_name: haproxy
    restart: always
    image: haproxy:2.2.4-alpine
    ports:
      - 8000:6301
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    environment:
      TZ: Asia/Shanghai
    networks:
      static-network:
        ipv4_address: 172.30.128.250 

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.30.0.0/16
