version: "3"
services:
  nginx_master:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx-master/index-master.html:/usr/share/nginx/html/index.html
      - ./nginx-master/favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./nginx-master/keepalived-master.conf:/etc/keepalived/keepalived.conf
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    cap_add: 
      - NET_ADMIN
  nginx_slave:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx-salve/index-slave.html:/usr/share/nginx/html/index.html
      - ./nginx-salve/favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./nginx-salve/keepalived-slave.conf:/etc/keepalived/keepalived.conf
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    cap_add: 
        - NET_ADMIN
  proxy:
    image: haproxy:2.2.4-alpine
    ports:
      - 8000:6301
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - static-network

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
