version: '3'

services:
  mongodb01:
    image: mongo
    restart: always
    container_name: mongo01
    volumes:
      - /app/mongodb/mongo01/data/db:/data/db
      - /app/mongodb/mongodb.key:/data/mongodb.key
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      - mongo
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh  $$@
  mongodb02:
    image: mongo
    restart: always
    container_name: mongo02
    volumes:
      - /app/mongodb/mongo02/data/db:/data/db
      - /app/mongodb/mongodb.key:/data/mongodb.key
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      - mongo
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh  $$@
  mongodb03:
    image: mongo
    restart: always
    container_name: mongo03
    volumes:
      - /app/mongodb/mongo03/data/db:/data/db
      - /app/mongodb/mongodb.key:/data/mongodb.key
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      - mongo
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh  $$@

networks:
  mongo:
    driver: bridge
