version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    privileged: true
    volumes:
      - /app/nginx/conf/proxy.conf:/etc/nginx/proxy.conf
      - /app/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /app/nginx/conf/conf.d/:/etc/nginx/conf.d/
      - /app/nginx/html/:/usr/share/nginx/html/
      - /app/nginx/logs/:/var/log/nginx/
    networks:
      - nginx-network
networks:
  office-nginx:
    driver: bridge
